"""
PyRill - Python client for Rill Data API

A unified Python SDK for interacting with Rill Data's API and CLI.
"""

from .client import RillClient
from .config import RillConfig
from .exceptions import RillError, RillAuthError, RillAPIError, RillCLIError
from .query_builder import QueryBuilder
from .url_builder import UrlBuilder
from .models import (
    Org,
    Project,
    Token,
    User,
    ProjectResources,
    Resource,
    Deployment,
    ProjectStatus,
    ProjectStatusInfo,
    DeploymentStatusInfo,
    ResourceName,
    MagicAuthToken,
    CreatePublicUrlResponse,
    # Query models
    Operator,
    TimeGrain,
    Expression,
    Condition,
    Dimension,
    DimensionCompute,
    DimensionComputeTimeFloor,
    Measure,
    MeasureCompute,
    MeasureComputeCountDistinct,
    MeasureComputeComparisonValue,
    MeasureComputeComparisonDelta,
    MeasureComputeComparisonRatio,
    MeasureComputePercentOfTotal,
    MeasureComputeURI,
    Subquery,
    Sort,
    TimeRange,
    TimeSpine,
    WhereSpine,
    Spine,
    MetricsQuery,
    MetricsSqlQuery,
    SqlQuery,
    QueryResult,
    # Annotation models
    Annotation,
    AnnotationsQuery,
    AnnotationsResponse,
    # Navigation models
    RillUrl,
    # Report models
    ExportFormat,
    Schedule,
    Notifier,
    ReportSpec,
    ReportExecution,
    ReportState,
    Report,
    ReportOptions,
    CreateReportResponse,
    EditReportResponse,
    DeleteReportResponse,
    TriggerReportResponse,
    UnsubscribeReportResponse,
    GenerateReportYAMLResponse,
    # Partition models
    ModelPartition,
    PartitionsList,
    # User and usergroup models
    OrganizationMemberUser,
    MemberUsergroup,
    Usergroup,
    # Alert models
    Alert,
    AlertOptions,
    AlertSpec,
    AlertExecution,
    AlertState,
    CreateAlertResponse,
    EditAlertResponse,
    DeleteAlertResponse,
    UnsubscribeAlertResponse,
    GetAlertYAMLResponse,
    GenerateAlertYAMLResponse,
    # Annotation models
    Annotation,
    AnnotationsQuery,
    AnnotationsResponse,
    # IFrame models
    IFrameOptions,
    IFrameResponse,
)
from .logging import ClientLogger, NullLogger, LogLevel
from .resources import AuthResource, OrgsResource, ProjectsResource, QueryResource, ReportsResource, AlertsResource, AnnotationsResource, IFramesResource, PartitionsResource, UsersResource, UsergroupsResource, PublicUrlsResource

__version__ = "0.2.0"
__all__ = [
    "RillClient",
    "RillConfig",
    "RillError",
    "RillAuthError",
    "RillAPIError",
    "RillCLIError",
    "QueryBuilder",
    "UrlBuilder",
    "Org",
    "Project",
    "Token",
    "User",
    "Deployment",
    "ProjectResources",
    "Resource",
    "ProjectStatus",
    "ProjectStatusInfo",
    "DeploymentStatusInfo",
    "ResourceName",
    "MagicAuthToken",
    "CreatePublicUrlResponse",
    "ClientLogger",
    "NullLogger",
    "LogLevel",
    "AuthResource",
    "OrgsResource",
    "ProjectsResource",
    "QueryResource",
    "AnnotationsResource",
    "ReportsResource",
    "AlertsResource",
    "AnnotationsResource",
    "IFramesResource",
    "PartitionsResource",
    "UsersResource",
    "UsergroupsResource",
    "PublicUrlsResource",
    # Query models
    "Operator",
    "TimeGrain",
    "Expression",
    "Condition",
    "Dimension",
    "DimensionCompute",
    "DimensionComputeTimeFloor",
    "Measure",
    "MeasureCompute",
    "MeasureComputeCountDistinct",
    "MeasureComputeComparisonValue",
    "MeasureComputeComparisonDelta",
    "MeasureComputeComparisonRatio",
    "MeasureComputePercentOfTotal",
    "MeasureComputeURI",
    "Subquery",
    "Sort",
    "TimeRange",
    "TimeSpine",
    "WhereSpine",
    "Spine",
    "MetricsQuery",
    "MetricsSqlQuery",
    "SqlQuery",
    "QueryResult",
    # Annotation models
    "Annotation",
    "AnnotationsQuery",
    "AnnotationsResponse",
    # Navigation models
    "RillUrl",
    # Report models
    "ExportFormat",
    "Schedule",
    "Notifier",
    "ReportSpec",
    "ReportExecution",
    "ReportState",
    "Report",
    "ReportOptions",
    "CreateReportResponse",
    "EditReportResponse",
    "DeleteReportResponse",
    "TriggerReportResponse",
    "UnsubscribeReportResponse",
    "GenerateReportYAMLResponse",
    # Partition models
    "ModelPartition",
    "PartitionsList",
    # User and usergroup models
    "OrganizationMemberUser",
    "MemberUsergroup",
    "Usergroup",
    # Alert models
    "Alert",
    "AlertOptions",
    "AlertSpec",
    "AlertExecution",
    "AlertState",
    "CreateAlertResponse",
    "EditAlertResponse",
    "DeleteAlertResponse",
    "UnsubscribeAlertResponse",
    "GetAlertYAMLResponse",
    "GenerateAlertYAMLResponse",
    # Annotation models
    "Annotation",
    "AnnotationsQuery",
    "AnnotationsResponse",
    # IFrame models
    "IFrameOptions",
    "IFrameResponse",
]
